"""
Show Models
Defines show drafts (pre-simulation) and show results (post-simulation).
NOW WITH SEGMENTS SUPPORT
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from models.match import MatchDraft, MatchResult


@dataclass
class SegmentDraft:
    """
    Pre-simulation segment plan.
    Simplified version for show drafts from frontend.
    """
    segment_id: str
    segment_type: str
    participants: List[Dict[str, Any]] = field(default_factory=list)
    feud_id: Optional[str] = None
    title_id: Optional[str] = None
    title_name: Optional[str] = None
    tone: str = 'intense'
    purpose: str = 'general'
    duration_minutes: int = 5
    card_position: int = 0
    is_opening: bool = False
    ends_in_brawl: bool = False
    causes_injury: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'segment_id': self.segment_id,
            'segment_type': self.segment_type,
            'participants': self.participants,
            'feud_id': self.feud_id,
            'title_id': self.title_id,
            'title_name': self.title_name,
            'tone': self.tone,
            'purpose': self.purpose,
            'duration_minutes': self.duration_minutes,
            'card_position': self.card_position,
            'is_opening': self.is_opening,
            'ends_in_brawl': self.ends_in_brawl,
            'causes_injury': self.causes_injury
        }
    
    @staticmethod
    def from_dict(data: Dict[str, Any]) -> 'SegmentDraft':
        return SegmentDraft(
            segment_id=data.get('segment_id', f"segment_{id(data)}"),
            segment_type=data.get('segment_type', 'promo'),
            participants=data.get('participants', []),
            feud_id=data.get('feud_id'),
            title_id=data.get('title_id'),
            title_name=data.get('title_name'),
            tone=data.get('tone', 'intense'),
            purpose=data.get('purpose', 'general'),
            duration_minutes=data.get('duration_minutes', 5),
            card_position=data.get('card_position', 0),
            is_opening=data.get('is_opening', False),
            ends_in_brawl=data.get('ends_in_brawl', False),
            causes_injury=data.get('causes_injury', False)
        )


@dataclass
class SegmentResult:
    """
    Post-simulation segment result.
    Simplified version for show results.
    """
    segment_id: str
    segment_type: str
    participants: List[Dict[str, Any]] = field(default_factory=list)
    
    # Timing
    duration_minutes: int = 5
    
    # Quality metrics
    segment_rating: float = 0.0
    crowd_heat: int = 0
    
    # Content
    key_moments: List[str] = field(default_factory=list)
    
    # Outcomes
    winner_id: Optional[str] = None
    winner_name: Optional[str] = None
    feud_intensity_change: int = 0
    momentum_changes: Dict[str, int] = field(default_factory=dict)
    popularity_changes: Dict[str, int] = field(default_factory=dict)
    
    # Special flags
    is_memorable: bool = False
    created_feud: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'segment_id': self.segment_id,
            'segment_type': self.segment_type,
            'participants': self.participants,
            'duration_minutes': self.duration_minutes,
            'segment_rating': self.segment_rating,
            'crowd_heat': self.crowd_heat,
            'key_moments': self.key_moments,
            'winner_id': self.winner_id,
            'winner_name': self.winner_name,
            'feud_intensity_change': self.feud_intensity_change,
            'momentum_changes': self.momentum_changes,
            'popularity_changes': self.popularity_changes,
            'is_memorable': self.is_memorable,
            'created_feud': self.created_feud
        }


@dataclass
class ShowDraft:
    """
    Pre-simulation show card.
    Generated by AI Creative Director or manual booking.
    """
    show_id: str
    show_name: str
    brand: str  # 'ROC Alpha', 'ROC Velocity', 'ROC Vanguard', 'Cross-Brand'
    show_type: str  # 'weekly_tv', 'minor_ppv', 'major_ppv'
    is_ppv: bool
    year: int
    week: int
    matches: List[MatchDraft] = field(default_factory=list)
    segments: List[SegmentDraft] = field(default_factory=list)
    
    def add_match(self, match: MatchDraft):
        """Add a match to the card"""
        self.matches.append(match)
    
    def add_segment(self, segment: SegmentDraft):
        """Add a segment to the card"""
        self.segments.append(segment)
    
    def get_card_order(self) -> List[Dict[str, Any]]:
        """Get combined matches and segments in card order"""
        card = []
        
        # Add matches with their positions
        for match in self.matches:
            card.append({
                'type': 'match',
                'position': match.card_position,
                'item': match
            })
        
        # Add segments with their positions
        for segment in self.segments:
            card.append({
                'type': 'segment',
                'position': segment.card_position,
                'item': segment
            })
        
        # Sort by position
        card.sort(key=lambda x: x['position'])
        
        return card
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'show_id': self.show_id,
            'show_name': self.show_name,
            'brand': self.brand,
            'show_type': self.show_type,
            'is_ppv': self.is_ppv,
            'year': self.year,
            'week': self.week,
            'match_count': len(self.matches),
            'segment_count': len(self.segments),
            'matches': [m.to_dict() for m in self.matches],
            'segments': [s.to_dict() for s in self.segments]
        }
    
    @staticmethod
    def from_dict(data: Dict[str, Any]) -> 'ShowDraft':
        draft = ShowDraft(
            show_id=data['show_id'],
            show_name=data['show_name'],
            brand=data['brand'],
            show_type=data['show_type'],
            is_ppv=data.get('is_ppv', False),
            year=data['year'],
            week=data['week']
        )
        
        # Parse matches
        for match_data in data.get('matches', []):
            draft.matches.append(MatchDraft.from_dict(match_data))
        
        # Parse segments
        for segment_data in data.get('segments', []):
            draft.segments.append(SegmentDraft.from_dict(segment_data))
        
        return draft


@dataclass
class ShowResult:
    """
    Post-simulation show result.
    Contains all match results, segment results, and show-level statistics.
    """
    show_id: str
    show_name: str
    brand: str
    show_type: str
    year: int
    week: int
    is_ppv: bool = False
    match_results: List[MatchResult] = field(default_factory=list)
    segment_results: List[SegmentResult] = field(default_factory=list)
    
    # Show-level stats
    overall_rating: float = 0.0
    match_rating: float = 0.0
    segment_rating: float = 0.0
    total_attendance: int = 0
    total_revenue: int = 0
    total_payroll: int = 0
    net_profit: int = 0
    
    # Event log
    events: List[Dict[str, Any]] = field(default_factory=list)
    
    # Step 63/72: Pacing report (attached after simulation)
    pacing_report: Optional[Dict[str, Any]] = None
    
    def add_match_result(self, result: MatchResult):
        """Add a match result"""
        self.match_results.append(result)
    
    def add_segment_result(self, result: SegmentResult):
        """Add a segment result"""
        self.segment_results.append(result)
    
    def add_event(self, event_type: str, description: str, **kwargs):
        """Add an event to the log"""
        event = {
            'type': event_type,
            'description': description,
            **kwargs
        }
        self.events.append(event)
    
    def calculate_ratings(self):
        """Calculate overall, match, and segment ratings"""
        # Match rating
        if self.match_results:
            self.match_rating = sum(m.star_rating for m in self.match_results) / len(self.match_results)
        
        # Segment rating
        if self.segment_results:
            self.segment_rating = sum(s.segment_rating for s in self.segment_results) / len(self.segment_results)
        
        # Overall rating (weighted: matches 70%, segments 30%)
        total_items = len(self.match_results) + len(self.segment_results)
        
        if total_items > 0:
            if self.match_results and self.segment_results:
                # Both present - weighted average
                self.overall_rating = (self.match_rating * 0.7) + (self.segment_rating * 0.3)
            elif self.match_results:
                # Only matches
                self.overall_rating = self.match_rating
            else:
                # Only segments
                self.overall_rating = self.segment_rating
        else:
            self.overall_rating = 0.0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'show_id': self.show_id,
            'show_name': self.show_name,
            'brand': self.brand,
            'show_type': self.show_type,
            'year': self.year,
            'week': self.week,
            'is_ppv': self.is_ppv,
            'match_count': len(self.match_results),
            'segment_count': len(self.segment_results),
            'match_results': [m.to_dict() for m in self.match_results],
            'segment_results': [s.to_dict() for s in self.segment_results],
            'overall_rating': self.overall_rating,
            'match_rating': self.match_rating,
            'segment_rating': self.segment_rating,
            'total_attendance': self.total_attendance,
            'total_revenue': self.total_revenue,
            'total_payroll': self.total_payroll,
            'net_profit': self.net_profit,
            'events': self.events,
            'pacing_report': getattr(self, 'pacing_report', None),
            'revenue_breakdown': getattr(self, 'revenue_breakdown', None),
            'expense_breakdown': getattr(self, 'expense_breakdown', None),
            'profit_projection': getattr(self, 'profit_projection', None),
            'profit_warnings': getattr(self, 'profit_warnings', []),
            'profit_recommendations': getattr(self, 'profit_recommendations', []),
        }
